version: '3.6'
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
      - ./wiley_dth.xml:/var/www/FreshRSS/p/wiley_dth.xml
    environment:
      - TZ=Asia/Shanghai
      - CRON_MIN=15,45
